### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jeremyhu** [glessard/swift-atomics#13]
The code in this repository have copyright, but there is no license given for its usage.  Please add a license file to give license to others to reuse/modify/redistribute your code as you see fit.

I see you chose MIT for swift-channels, so I presume you want the same here.

**Comment by glessard** [comment]
Good point. I think I uploaded this after many commits, so I wasn't prompted for a license until now! I have a branch going, I'll update the copyright notices and then merge. Thanks!

**Comment by glessard** [comment]
Done. I hope this will be satisfactory.
