### ISSUE TITLE
AtomicTaggedReference

### ISSUE THREAD

**Issue by lbrndnr** [glessard/swift-atomics#38]
Hi Guillaume, 
I saw that you added an AtomicTaggedPointer and was wondering whether you planned working on a tagged reference, too? I would be happy to help if you haven't started working on it already :)

**Comment by glessard** [comment]
If you have a need for it, then by all means make it. Note that I haven't made any of the nicer calls for the tagged pointers on the Swift side in Atomics; it's all just defined in C (with Swift-ified function names) in CAtomics.

**Comment by glessard** [comment]
Have you had success building a lock-free algorithm around an atomic reference?

**Comment by lbrndnr** [comment]
Sorry, currently quite busy, so I couldn't find the time to work on it just yet. 
A lock free version of the current reference implementation would certainly be possible but I think it might turn out to be quite complicated and not necessarily more performant. So I'm not sure it makes sense to work on that. What are your thoughts on this?
I want this mostly for an implementation of a lock free linked list. I realized though that this scenario does not require the atomic reference to retain the pointee.

**Comment by glessard** [comment]
I think that to do a fully lock-free queue with general ARC-enabled memory you have to add another layer of memory management. That would be quite a hit on performance.
If you need a lock-free linked list whose object type is a reference, you can probably lightly wrap the Michael-Scott algorithm and have it traffic in Unmanaged. That way you can push the ARC activity completely outside of the critical sections.

**Comment by lbrndnr** [comment]
Exactly, I think that's what I'll be using. Is there any particular reason for AtomicTaggedPointer to not support optional types? It doesn't seem like I can CAS it with optionals, nor any other function actually.

**Comment by glessard** [comment]
The atomic tagged pointer stuff has 4 pairs of types Tagged{Optional}{Mutable}RawPointer. There are cases where you need to deal with an optional pointer, but I also wanted an option for when you never deal with a nil pointer. (It's generated by a macro anyway, so there isn't much extra effort involved.)

**Comment by lbrndnr** [comment]
You're right, thank you :)

**Comment by glessard** [comment]
If I may, what is a case where you'd need a tagged reference? Tagged pointers are a solution to the ABA problem, where a pointer gets deallocated and then reallocated while a thread is suspended. In the case of an ARC reference, the memory can't get deallocated because it's actively being referred to by the thread that is suspended -- this eliminates the ABA problem entirely. Do you have another use in mind for the tagged reference?

**Comment by lbrndnr** [comment]
Atomic tagged pointers allow the implementation of a lock-free linked list: https://github.com/lbrndnr/AtomicLinkedList. But we don't have to merge it if you don't like to, I can also just add it as an extension in my repository. Sorry for the delayed answer btw, I had exams the last couple of weeks ;)

**Comment by glessard** [comment]
The tag is used for a single state bit in that algorithm, then? In this case, wouldn't it be a more efficient to lightly modify the existing AtomicReference and store it in its (never used) least-significant bit?

**Comment by lbrndnr** [comment]
Exactly, yes I guess that's actually also how java implements it :) I just figured it would be generally more useful the way I implemented it. But I guess I'll make it use the least significant bits then 👍

**Comment by glessard** [comment]
Hi Laurin, I've decided to close https://github.com/glessard/swift-atomics/pull/44, as this hasn't progressed in a long time.
